# Generated by Django 4.1.1 on 2022-09-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='TradeTypeSpelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=255)),
                ('trade_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_banking.tradetype')),
            ],
            options={
                'ordering': ['spelling'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('net', models.FloatField()),
                ('vat', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_banking.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_banking.currency')),
                ('trade_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_banking.tradetype')),
            ],
        ),
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField()),
                ('processing_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_banking.processingstatus')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
